version: "2"
linters:
  default: all
  disable:
    - nonamedreturns
    - varnamelen
  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          allow:
            - golang.org/x/crypto/*
    errcheck:
      check-type-assertions: true
      check-blank: true
    funlen:
      lines: 120
    gocritic:
      enable-all: true
    gosec:
      excludes:
        - G115
    govet:
      enable-all: true
      settings:
        shadow:
          strict: true
    ireturn:
      allow:
        - generic
    mnd:
      checks:
        - argument
        - case
        - condition
        - operation
        - return
        - assign
      ignored-numbers:
        - '2'
        - '3'
        - '4'
        - '7'
        - '8'
        - '32'
        - '48'
        - '64'
        - '66'
        - '72'
        - '98'
    nlreturn:
      block-size: 2
    prealloc:
      simple: false
      for-loops: true
  exclusions:
    rules:
      - path: nist/p256/p256.go
        linters:
          - gochecknoglobals
      - path: nist/p384/p384.go
        linters:
          - gochecknoglobals
      - path: nist/p521/p521.go
        linters:
          - gochecknoglobals
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/bytemare/hash2curve)
        - blank
        - dot
        - alias
      no-inline-comments: true
      no-prefix-comments: true
      custom-order: true
    goimports:
      local-prefixes:
        - github.com/bytemare/hash2curve
    golines:
      max-len: 200
output:
  sort-order:
    - file
run:
  tests: false