name: Scorecard Analysis Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # Weekly on Saturdays.
    - cron: '30 1 * * 6'

permissions: {}

jobs:
  analysis:
    permissions:
      # Needed if using Code scanning alerts
      security-events: write
      # Needed for GitHub OIDC token if publish_results is true
      id-token: write
      # Needed for nested workflow
      actions: read
      attestations: read
      checks: read
      contents: read
      deployments: read
      issues: read
      discussions: read
      packages: read
      pages: read
      pull-requests: read
      repository-projects: read
      statuses: read

    uses: bytemare/workflows/.github/workflows/scorecard.yml@6a1ecd61e6af01d166be3eaa6d38fcecf7754c08
    secrets:
      token: ${{ secrets.SCORECARD_TOKEN }}