name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  Test:
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.24', '1.23', '1.22' ]
    uses: bytemare/workflows/.github/workflows/test-go.yaml@35817f8d486a2b102d015a808ba04dcf5e003fcd
    with:
      version: ${{ matrix.go }}
