name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  Test:
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.24' ]
    uses: bytemare/workflows/.github/workflows/test-go.yml@fe18ca952aa0f46bf9d10a8121b9f93ccbf416f7
    with:
      command: cd .github && make test
      version: ${{ matrix.go }}
