name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  Test:
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.24', '1.23', '1.22' ]
    uses: bytemare/workflows/.github/workflows/test-go.yaml@5ee47c25a5c79c9588f25caa46c180240f2367d5
    with:
      version: ${{ matrix.go }}
